# Generated by Django 6.0.1 on 2026-01-26 12:48

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_created_date_product_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
