# Generated by Django 6.0.1 on 2026-01-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment_order_payment_orderproduct_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
